import Link from "next/link";
import { Brand } from "@/components/brand";
import { vercelDeployUrl } from "@/lib/vercel-deploy";

const repositoryUrl = process.env.NEXT_PUBLIC_TEMPLATE_REPOSITORY_URL
  ?? (process.env.VERCEL_GIT_REPO_OWNER && process.env.VERCEL_GIT_REPO_SLUG
    ? `https://github.com/${process.env.VERCEL_GIT_REPO_OWNER}/${process.env.VERCEL_GIT_REPO_SLUG}`
    : undefined);

export default function InstallationHelpPage() {
  const deployUrl = repositoryUrl ? vercelDeployUrl(repositoryUrl) : null;

  return (
    <main className="help-page">
      <nav className="help-nav"><Brand /><Link href="/setup">Return to setup</Link></nav>
      <header className="help-hero">
        <span className="auth-step">Vercel + Supabase</span>
        <h1>An independent installation<br />without server administration.</h1>
        <p>Every community has its own code copy, Vercel project and Supabase database. No installation depends on a central application server.</p>
        {deployUrl ? <a className="button button-accent" href={deployUrl}>Start the recommended installation</a> : <div className="setup-warning">The template distributor must configure the public GitHub template URL in <code>NEXT_PUBLIC_TEMPLATE_REPOSITORY_URL</code>.</div>}
      </header>

      <section className="help-options">
        <article className="help-option recommended">
          <span>Recommended</span><h2>One Vercel deployment button</h2>
          <ol>
            <li>Sign in to Vercel and choose the GitHub account that will own your project copy.</li>
            <li>Choose a unique installation secret for <code>SETUP_SECRET</code>.</li>
            <li>Confirm the Supabase product, plan and database region.</li>
            <li>Vercel connects the Supabase credentials and deploys the application.</li>
            <li>Open the application and complete the first-run wizard.</li>
          </ol>
        </article>
        <article className="help-option">
          <span>If the Supabase step is missing</span><h2>Connect it in the Vercel dashboard</h2>
          <ol>
            <li>Deploy the GitHub copy to Vercel first.</li>
            <li>In the Vercel project, open <b>Storage → Create Database → Supabase</b>.</li>
            <li>Create a Supabase project and connect it to this Vercel project.</li>
            <li>Add <code>SETUP_SECRET</code> under Project Settings → Environment Variables.</li>
            <li><b>Redeploy</b>, then open <code>/setup</code>.</li>
          </ol>
        </article>
        <article className="help-option">
          <span>Existing Supabase project</span><h2>Manual connection</h2>
          <ol>
            <li>Import your GitHub copy into Vercel.</li>
            <li>Add <code>DATABASE_URL</code> or <code>POSTGRES_URL</code> with the pooled Supabase connection string.</li>
            <li>Add <code>SUPABASE_SECRET_KEY</code> and your <code>SETUP_SECRET</code>.</li>
            <li>Redeploy. Database migrations run automatically during the build.</li>
            <li>Complete the configuration in the application wizard.</li>
          </ol>
        </article>
      </section>

      <section className="help-detail">
        <div><span className="section-number">Security</span><h2>Where are credentials stored?</h2></div>
        <div className="help-facts">
          <p><b>Database credentials</b><span>Vercel Environment Variables. They are never stored in GitHub or exposed to the browser.</span></p>
          <p><b>Meta App Secret</b><span>The wizard encrypts it before storing it in this instance’s Supabase database.</span></p>
          <p><b>Federation private key</b><span>Generated by the wizard and encrypted in this instance’s database.</span></p>
          <p><b>Installation secret</b><span>Stored only in Vercel; the wizard verifies it and never writes it to the database.</span></p>
        </div>
      </section>

      <section className="help-detail whatsapp-help">
        <div><span className="section-number">WhatsApp</span><h2>What must be prepared in Meta?</h2></div>
        <div className="help-facts">
          <p><b>1. Meta app</b><span>Create a Business app and add the WhatsApp product.</span></p>
          <p><b>2. Community number</b><span>Connect the WhatsApp Business number to which members send the authentication message.</span></p>
          <p><b>3. App Secret</b><span>Paste it into the WhatsApp step of the wizard. It will not be shown again in the browser.</span></p>
          <p><b>4. Webhook</b><span>After installation, copy the Callback URL and Verify token, then subscribe to <code>messages</code>.</span></p>
        </div>
      </section>
    </main>
  );
}
